const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.ScriptsInEvents.FolhaDeEventos1_Event15_Act4,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.FolhaDeEventos1_Event22,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{água: 0},
	{Bandeira: 0},
	{TextoFim: 0},
	{Botão: 0},
	{JogadorAnim: 0},
	{Teclado: 0},
	{Pontos: 0},
	{Áudio: 0},
	{AVBMO: 0},
	{Jogar: 0},
	{Botão2: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{Senóide: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{golem_inimigo: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Mosaico2: 0},
	{espinho: 0},
	{Portal: 0},
	{Arbusto: 0},
	{engrenagens: 0},
	{Texto: 0},
	{Mouse: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto2: 0},
	{Sprite5: 0}
];

self.InstanceType = {
	Jogador: class extends self.ISpriteInstance {},
	água: class extends self.ISpriteInstance {},
	Bandeira: class extends self.ISpriteInstance {},
	TextoFim: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	JogadorAnim: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Pontos: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	AVBMO: class extends self.ITextInstance {},
	Jogar: class extends self.IButtonInstance {},
	Botão2: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	golem_inimigo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	espinho: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Arbusto: class extends self.ISpriteInstance {},
	engrenagens: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}